import type {
  AdminNoteRecord,
  AdminActivityLogRecord,
  BookingRecord,
  HireRecord,
  PortfolioImageRecord,
  SkillRecord,
  StaffingAssignmentRecord,
  TeamRequestRecord,
  TeamRequestRoleRecord,
  TeamRequestRoleSkillRecord,
  VerificationDocumentRecord,
  WorkerCategory,
  WorkerRecord,
  WorkerReferenceRecord,
  WorkerSkillRecord,
} from "@/lib/types";
import { defaultPaymentInstructions } from "@/lib/booking-workflow";

const portraits = {
  amara:
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
  baraka:
    "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
  leila:
    "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80",
  zuri:
    "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
  eshe:
    "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
  aisha:
    "https://images.unsplash.com/photo-1524504388940-b1c1722653c1?auto=format&fit=crop&w=900&q=80",
  imaan:
    "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
  thando:
    "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=900&q=80",
  joy:
    "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
  malik:
    "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
  nadia:
    "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
  farah:
    "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?auto=format&fit=crop&w=900&q=80",
} as const;

const portfolioShots = {
  color:
    "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
  nail:
    "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=1200&q=80",
  barber:
    "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=80",
  makeup:
    "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80",
  spa:
    "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=1200&q=80",
  lashes:
    "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=1200&q=80",
  braids:
    "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=1200&q=80",
  wig:
    "https://images.unsplash.com/photo-1519741491158-4a9f9a70c6f1?auto=format&fit=crop&w=1200&q=80",
} as const;

export const workerCategories: WorkerCategory[] = [
  {
    role: "Hair Stylist",
    description:
      "Color, treatments, silk presses, and daily salon styling.",
    typical_team_use:
      "Main floor coverage for cuts, color, washing, and styling.",
  },
  {
    role: "Barber",
    description:
      "Fade, beard, and grooming workers for busy appointment books.",
    typical_team_use:
      "Fast chair coverage for grooming and walk-in schedules.",
  },
  {
    role: "Nail Technician",
    description:
      "Gel, acrylic, nail art, and mani-pedi workers.",
    typical_team_use:
      "Useful for repeat clients, bridal prep, and add-on services.",
  },
  {
    role: "Makeup Artist",
    description:
      "Bridal, event, and photoshoot makeup workers.",
    typical_team_use: "Bridal weekends, events, launches, and photoshoots.",
  },
  {
    role: "Spa Therapist",
    description:
      "Massage, body treatment, and wellness workers.",
    typical_team_use:
      "Treatment-room coverage, package services, and spa bookings.",
  },
  {
    role: "Lash Technician",
    description:
      "Classic, hybrid, and volume lash workers.",
    typical_team_use:
      "Lash sets, refill appointments, and add-on services.",
  },
  {
    role: "Braider",
    description:
      "Braids, twists, and natural hair care workers.",
    typical_team_use: "Protective styles and busy seasonal bookings.",
  },
  {
    role: "Wig Specialist",
    description:
      "Wig installs, customization, and maintenance workers.",
    typical_team_use:
      "Install services, styling packages, and event prep.",
  },
];

export const skills: SkillRecord[] = [
  { id: "skill-color-correction", name: "Color Correction", role: "Hair Stylist" },
  { id: "skill-silk-press", name: "Silk Press", role: "Hair Stylist" },
  { id: "skill-scalp-treatment", name: "Scalp Treatments", role: "Hair Stylist" },
  { id: "skill-fades", name: "Fade Specialist", role: "Barber" },
  { id: "skill-beards", name: "Bald Specialist", role: "Barber" },
  { id: "skill-grooming", name: "Kids Cuts", role: "Barber" },
  { id: "skill-gel-x", name: "Gel-X Extensions", role: "Nail Technician" },
  { id: "skill-nail-art", name: "Nail Art", role: "Nail Technician" },
  { id: "skill-pedicure", name: "Spa Pedicures", role: "Nail Technician" },
  { id: "skill-bridal-makeup", name: "Bridal Makeup", role: "Makeup Artist" },
  { id: "skill-airbrush", name: "Airbrush Finish", role: "Makeup Artist" },
  { id: "skill-editorial", name: "Editorial Looks", role: "Makeup Artist" },
  { id: "skill-deep-tissue", name: "Deep Tissue Massage", role: "Spa Therapist" },
  { id: "skill-aromatherapy", name: "Aromatherapy", role: "Spa Therapist" },
  { id: "skill-body-polish", name: "Body Polish Treatments", role: "Spa Therapist" },
  { id: "skill-classic-lash", name: "Classic Lash Sets", role: "Lash Technician" },
  { id: "skill-volume-lash", name: "Volume Lash Sets", role: "Lash Technician" },
  { id: "skill-lash-lift", name: "Lash Lifts", role: "Lash Technician" },
  { id: "skill-knotless", name: "Knotless Braids", role: "Braider" },
  { id: "skill-boho-braids", name: "Boho Braids", role: "Braider" },
  { id: "skill-natural-care", name: "Natural Hair Prep", role: "Braider" },
  { id: "skill-frontal", name: "Frontal Installs", role: "Wig Specialist" },
  { id: "skill-custom-color", name: "Custom Wig Coloring", role: "Wig Specialist" },
  { id: "skill-revival", name: "Unit Revivals", role: "Wig Specialist" },
];

export const workers: WorkerRecord[] = [
  {
    id: "amara-njeri",
    full_name: "Amara Njeri",
    primary_role: "Hair Stylist",
    profile_photo: portraits.amara,
    location: "Nairobi",
    years_of_experience: 8,
    bio: "Amara blends precision coloring with a calm chairside experience and strong repeat-booking discipline.",
    availability_status: "reserved",
    verification_status: "verified",
    salary_expectation: 90000,
    work_type: "full-time",
    whatsapp_number: "+254 700 111 221",
    headline: "Reserved for a Nairobi expansion team after successful trial day feedback.",
    featured: true,
    featured_status: "active",
    featured_expires_at: "2026-07-30",
    featured_frequency: 8,
    featured_priority_score: 96,
    listed_publicly: true,
  },
  {
    id: "baraka-otieno",
    full_name: "Baraka Otieno",
    primary_role: "Barber",
    profile_photo: portraits.baraka,
    location: "Nairobi",
    years_of_experience: 6,
    bio: "Baraka is known for clean fades, sharp beard architecture, and efficient grooming-floor workflow.",
    availability_status: "reserved",
    verification_status: "verified",
    salary_expectation: 70000,
    work_type: "contract",
    whatsapp_number: "+254 701 443 008",
    headline: "Currently held for an urgent grooming club request.",
    featured: true,
    featured_status: "active",
    featured_expires_at: "2026-07-12",
    featured_frequency: 7,
    featured_priority_score: 88,
    listed_publicly: true,
  },
  {
    id: "leila-hassan",
    full_name: "Leila Hassan",
    primary_role: "Nail Technician",
    profile_photo: portraits.leila,
    location: "Mombasa",
    years_of_experience: 5,
    bio: "Leila handles manicure and pedicure work with clean process and strong finish quality.",
    availability_status: "available",
    verification_status: "verified",
    salary_expectation: 65000,
    work_type: "full-time",
    whatsapp_number: "+254 708 555 210",
    headline: "Ready for mani-pedi floors and bridal prep demand.",
    featured: true,
    featured_status: "active",
    featured_expires_at: "2026-08-05",
    featured_frequency: 9,
    featured_priority_score: 92,
    listed_publicly: true,
  },
  {
    id: "zuri-kamau",
    full_name: "Zuri Kamau",
    primary_role: "Makeup Artist",
    profile_photo: portraits.zuri,
    location: "Nairobi",
    years_of_experience: 7,
    bio: "Zuri is strongest in bridal and photoshoot-ready glam, with polished client handoff and backstage rhythm.",
    availability_status: "hired",
    verification_status: "verified",
    salary_expectation: 85000,
    work_type: "freelance",
    whatsapp_number: "+254 722 201 105",
    headline: "Placed into a completed campaign staffing request.",
    featured: true,
    featured_status: "active",
    featured_expires_at: "2026-06-20",
    featured_frequency: 4,
    featured_priority_score: 76,
    listed_publicly: false,
  },
  {
    id: "eshe-mwangi",
    full_name: "Eshe Mwangi",
    primary_role: "Spa Therapist",
    profile_photo: portraits.eshe,
    location: "Kisumu",
    years_of_experience: 9,
    bio: "Eshe brings calm treatment-room energy, excellent consultations, and dependable service consistency.",
    availability_status: "hired",
    verification_status: "verified",
    salary_expectation: 78000,
    work_type: "full-time",
    whatsapp_number: "+254 733 404 915",
    headline: "Placed with a wellness-led spa and now marked as hired.",
    featured: false,
    featured_status: "off",
    featured_expires_at: null,
    featured_frequency: 0,
    featured_priority_score: 0,
    listed_publicly: false,
  },
  {
    id: "aisha-noor",
    full_name: "Aisha Noor",
    primary_role: "Lash Technician",
    profile_photo: portraits.aisha,
    location: "Nairobi",
    years_of_experience: 4,
    bio: "Aisha specializes in soft-volume sets and repeat maintenance bookings with a neat, scalable workflow.",
    availability_status: "available",
    verification_status: "pending",
    salary_expectation: 60000,
    work_type: "part-time",
    whatsapp_number: "+254 711 188 320",
    headline: "In onboarding while waiting on final verification documents.",
    featured: false,
    featured_status: "off",
    featured_expires_at: null,
    featured_frequency: 0,
    featured_priority_score: 0,
    listed_publicly: false,
  },
  {
    id: "imaan-abdi",
    full_name: "Imaan Abdi",
    primary_role: "Braider",
    profile_photo: portraits.imaan,
    location: "Mombasa",
    years_of_experience: 10,
    bio: "Imaan handles protective style demand with speed, clean parting, and calm long-appointment client care.",
    availability_status: "available",
    verification_status: "verified",
    salary_expectation: 82000,
    work_type: "contract",
    whatsapp_number: "+254 734 508 199",
    headline: "Strong fit for seasonal braid demand and destination bookings.",
    featured: false,
    featured_status: "off",
    featured_expires_at: null,
    featured_frequency: 0,
    featured_priority_score: 0,
    listed_publicly: true,
  },
  {
    id: "thando-mbeki",
    full_name: "Thando Mbeki",
    primary_role: "Wig Specialist",
    profile_photo: portraits.thando,
    location: "Nairobi",
    years_of_experience: 6,
    bio: "Thando is trusted for wig installs, customizations, and maintenance work.",
    availability_status: "available",
    verification_status: "verified",
    salary_expectation: 88000,
    work_type: "full-time",
    whatsapp_number: "+254 746 321 774",
    headline: "Verified and ready for transformation-led service menus.",
    featured: true,
    featured_status: "active",
    featured_expires_at: "2026-07-22",
    featured_frequency: 6,
    featured_priority_score: 84,
    listed_publicly: true,
  },
  {
    id: "joy-cherotich",
    full_name: "Joy Cherotich",
    primary_role: "Hair Stylist",
    profile_photo: portraits.joy,
    location: "Nakuru",
    years_of_experience: 3,
    bio: "Joy is a rising stylist with strong service discipline, healthy blowout consistency, and good salon floor adaptability.",
    availability_status: "available",
    verification_status: "pending",
    salary_expectation: 52000,
    work_type: "part-time",
    whatsapp_number: "+254 712 822 309",
    headline: "Recommended internally but not yet public until references clear.",
    featured: false,
    featured_status: "off",
    featured_expires_at: null,
    featured_frequency: 0,
    featured_priority_score: 0,
    listed_publicly: false,
  },
  {
    id: "malik-dube",
    full_name: "Malik Dube",
    primary_role: "Barber",
    profile_photo: portraits.malik,
    location: "Eldoret",
    years_of_experience: 11,
    bio: "Malik combines classic grooming standards with a fast, steady chair pace.",
    availability_status: "available",
    verification_status: "verified",
    salary_expectation: 76000,
    work_type: "full-time",
    whatsapp_number: "+254 724 141 550",
    headline: "Senior barber ready for memberships or lead-chair coverage.",
    featured: false,
    featured_status: "off",
    featured_expires_at: null,
    featured_frequency: 0,
    featured_priority_score: 0,
    listed_publicly: true,
  },
  {
    id: "nadia-aziz",
    full_name: "Nadia Aziz",
    primary_role: "Nail Technician",
    profile_photo: portraits.nadia,
    location: "Nairobi",
    years_of_experience: 8,
    bio: "Nadia is strong in manicure work where detail, sanitation, and neat design matter.",
    availability_status: "reserved",
    verification_status: "verified",
    salary_expectation: 72000,
    work_type: "full-time",
    whatsapp_number: "+254 713 990 144",
    headline: "Reserved for a branch opening with immediate manicure demand.",
    featured: false,
    featured_status: "off",
    featured_expires_at: null,
    featured_frequency: 0,
    featured_priority_score: 0,
    listed_publicly: true,
  },
  {
    id: "farah-juma",
    full_name: "Farah Juma",
    primary_role: "Makeup Artist",
    profile_photo: portraits.farah,
    location: "Mombasa",
    years_of_experience: 5,
    bio: "Farah delivers soft glam and camera-ready finishes, but is currently on hold pending updated references.",
    availability_status: "available",
    verification_status: "rejected",
    salary_expectation: 69000,
    work_type: "freelance",
    whatsapp_number: "+254 721 830 612",
    headline: "Rejected from public release until verification concerns are resolved.",
    featured: false,
    featured_status: "off",
    featured_expires_at: null,
    featured_frequency: 0,
    featured_priority_score: 0,
    listed_publicly: false,
  },
];

export const workerSkills: WorkerSkillRecord[] = [
  { id: "ws-1", worker_id: "amara-njeri", skill_id: "skill-color-correction", proficiency_level: "specialist" },
  { id: "ws-2", worker_id: "amara-njeri", skill_id: "skill-silk-press", proficiency_level: "advanced" },
  { id: "ws-3", worker_id: "amara-njeri", skill_id: "skill-scalp-treatment", proficiency_level: "advanced" },
  { id: "ws-4", worker_id: "baraka-otieno", skill_id: "skill-fades", proficiency_level: "specialist" },
  { id: "ws-5", worker_id: "baraka-otieno", skill_id: "skill-beards", proficiency_level: "advanced" },
  { id: "ws-6", worker_id: "baraka-otieno", skill_id: "skill-grooming", proficiency_level: "advanced" },
  { id: "ws-7", worker_id: "leila-hassan", skill_id: "skill-gel-x", proficiency_level: "specialist" },
  { id: "ws-8", worker_id: "leila-hassan", skill_id: "skill-nail-art", proficiency_level: "specialist" },
  { id: "ws-9", worker_id: "leila-hassan", skill_id: "skill-pedicure", proficiency_level: "advanced" },
  { id: "ws-10", worker_id: "zuri-kamau", skill_id: "skill-bridal-makeup", proficiency_level: "specialist" },
  { id: "ws-11", worker_id: "zuri-kamau", skill_id: "skill-airbrush", proficiency_level: "advanced" },
  { id: "ws-12", worker_id: "zuri-kamau", skill_id: "skill-editorial", proficiency_level: "advanced" },
  { id: "ws-13", worker_id: "eshe-mwangi", skill_id: "skill-deep-tissue", proficiency_level: "specialist" },
  { id: "ws-14", worker_id: "eshe-mwangi", skill_id: "skill-aromatherapy", proficiency_level: "advanced" },
  { id: "ws-15", worker_id: "eshe-mwangi", skill_id: "skill-body-polish", proficiency_level: "advanced" },
  { id: "ws-16", worker_id: "aisha-noor", skill_id: "skill-classic-lash", proficiency_level: "advanced" },
  { id: "ws-17", worker_id: "aisha-noor", skill_id: "skill-volume-lash", proficiency_level: "advanced" },
  { id: "ws-18", worker_id: "aisha-noor", skill_id: "skill-lash-lift", proficiency_level: "core" },
  { id: "ws-19", worker_id: "imaan-abdi", skill_id: "skill-knotless", proficiency_level: "specialist" },
  { id: "ws-20", worker_id: "imaan-abdi", skill_id: "skill-boho-braids", proficiency_level: "advanced" },
  { id: "ws-21", worker_id: "imaan-abdi", skill_id: "skill-natural-care", proficiency_level: "advanced" },
  { id: "ws-22", worker_id: "thando-mbeki", skill_id: "skill-frontal", proficiency_level: "specialist" },
  { id: "ws-23", worker_id: "thando-mbeki", skill_id: "skill-custom-color", proficiency_level: "advanced" },
  { id: "ws-24", worker_id: "thando-mbeki", skill_id: "skill-revival", proficiency_level: "advanced" },
  { id: "ws-25", worker_id: "joy-cherotich", skill_id: "skill-silk-press", proficiency_level: "core" },
  { id: "ws-26", worker_id: "joy-cherotich", skill_id: "skill-scalp-treatment", proficiency_level: "core" },
  { id: "ws-27", worker_id: "malik-dube", skill_id: "skill-fades", proficiency_level: "advanced" },
  { id: "ws-28", worker_id: "malik-dube", skill_id: "skill-beards", proficiency_level: "specialist" },
  { id: "ws-29", worker_id: "nadia-aziz", skill_id: "skill-gel-x", proficiency_level: "advanced" },
  { id: "ws-30", worker_id: "nadia-aziz", skill_id: "skill-pedicure", proficiency_level: "specialist" },
  { id: "ws-31", worker_id: "farah-juma", skill_id: "skill-bridal-makeup", proficiency_level: "advanced" },
  { id: "ws-32", worker_id: "farah-juma", skill_id: "skill-editorial", proficiency_level: "core" },
];

export const portfolioImages: PortfolioImageRecord[] = [
  { id: "pi-1", worker_id: "amara-njeri", image_url: portfolioShots.color, caption: "Dimensional blonde refresh", is_cover: true },
  { id: "pi-2", worker_id: "baraka-otieno", image_url: portfolioShots.barber, caption: "Low fade and beard refinement", is_cover: true },
  { id: "pi-3", worker_id: "leila-hassan", image_url: portfolioShots.nail, caption: "Structured nude Gel-X set", is_cover: true },
  { id: "pi-4", worker_id: "zuri-kamau", image_url: portfolioShots.makeup, caption: "Bridal soft glam", is_cover: true },
  { id: "pi-5", worker_id: "eshe-mwangi", image_url: portfolioShots.spa, caption: "Calming treatment room setup", is_cover: true },
  { id: "pi-6", worker_id: "aisha-noor", image_url: portfolioShots.lashes, caption: "Wispy hybrid lash set", is_cover: true },
  { id: "pi-7", worker_id: "imaan-abdi", image_url: portfolioShots.braids, caption: "Waist-length knotless finish", is_cover: true },
  { id: "pi-8", worker_id: "thando-mbeki", image_url: portfolioShots.wig, caption: "HD frontal customization", is_cover: true },
  { id: "pi-9", worker_id: "joy-cherotich", image_url: portfolioShots.color, caption: "Smooth blowout service", is_cover: true },
  { id: "pi-10", worker_id: "malik-dube", image_url: portfolioShots.barber, caption: "Classic scissor-over-comb finish", is_cover: true },
  { id: "pi-11", worker_id: "nadia-aziz", image_url: portfolioShots.nail, caption: "Clean mani-pedi set", is_cover: true },
  { id: "pi-12", worker_id: "farah-juma", image_url: portfolioShots.makeup, caption: "Destination bridal glow", is_cover: true },
];

export const workerReferences: WorkerReferenceRecord[] = [
  { id: "ref-1", worker_id: "amara-njeri", contact_name: "Janet Wambui", contact_phone: "+254 721 111 902", relationship: "Former salon manager", previous_workplace: "Oak and Ember Salon" },
  { id: "ref-2", worker_id: "baraka-otieno", contact_name: "Victor Kariuki", contact_phone: "+254 703 224 908", relationship: "Shop owner", previous_workplace: "Crown Grooming Club" },
  { id: "ref-3", worker_id: "leila-hassan", contact_name: "Muna Ali", contact_phone: "+254 711 506 100", relationship: "Spa lead", previous_workplace: "Pearl Coast Lounge" },
  { id: "ref-4", worker_id: "zuri-kamau", contact_name: "Cynthia Maina", contact_phone: "+254 733 009 880", relationship: "Production coordinator", previous_workplace: "Muse Bridal Studio" },
  { id: "ref-5", worker_id: "eshe-mwangi", contact_name: "Lilian Ouma", contact_phone: "+254 720 403 918", relationship: "Wellness director", previous_workplace: "Lakeview Wellness House" },
  { id: "ref-6", worker_id: "aisha-noor", contact_name: "Fauzia Ahmed", contact_phone: "+254 714 992 334", relationship: "Beauty bar owner", previous_workplace: "The Lash Room" },
  { id: "ref-7", worker_id: "imaan-abdi", contact_name: "Nasra Said", contact_phone: "+254 701 882 120", relationship: "Salon supervisor", previous_workplace: "Coast Texture Studio" },
  { id: "ref-8", worker_id: "thando-mbeki", contact_name: "Ruth Kosgei", contact_phone: "+254 734 500 712", relationship: "Creative lead", previous_workplace: "Velvet Install Lab" },
  { id: "ref-9", worker_id: "joy-cherotich", contact_name: "Beatrice Kigen", contact_phone: "+254 710 440 902", relationship: "Shift lead", previous_workplace: "Golden Blowdry Bar" },
  { id: "ref-10", worker_id: "malik-dube", contact_name: "Samuel Cheruiyot", contact_phone: "+254 722 304 100", relationship: "Barbershop owner", previous_workplace: "Northline Grooming" },
  { id: "ref-11", worker_id: "nadia-aziz", contact_name: "Farida Yusuf", contact_phone: "+254 705 987 661", relationship: "Studio manager", previous_workplace: "Lustre Nail Atelier" },
  { id: "ref-12", worker_id: "farah-juma", contact_name: "Amina Salim", contact_phone: "+254 730 110 234", relationship: "Event lead", previous_workplace: "Coastline Bridal House" },
];

export const teamRequests: TeamRequestRecord[] = [
  {
    id: "req-luna-house",
    salon_name: "Luna House Salon",
    contact_name: "Martha Wainaina",
    contact_email: "martha@lunahouse.example",
    contact_whatsapp: "+254 745 111 777",
    location: "Nairobi",
    verified_only: true,
    work_type: "long-term-contract",
    urgency: "priority",
    status: "staffing",
    notes: "Second branch launch. Needs workers ready for opening week.",
    target_start_date: "2026-05-28",
    submitted_at: "2026-05-03T09:15:00.000Z",
  },
  {
    id: "req-baroque-grooming",
    salon_name: "Baroque Grooming Club",
    contact_name: "Kevin Maina",
    contact_email: "kevin@baroque.example",
    contact_whatsapp: "+254 709 880 191",
    location: "Nairobi",
    verified_only: true,
    work_type: "short-term-contract",
    urgency: "urgent",
    status: "reviewing",
    notes: "Needs chair-ready barbers for membership traffic and walk-ins within two weeks.",
    target_start_date: "2026-06-05",
    submitted_at: "2026-05-07T14:05:00.000Z",
  },
  {
    id: "req-coastline-beauty",
    salon_name: "Coastline Beauty Lounge",
    contact_name: "Amina Salim",
    contact_email: "amina@coastline.example",
    contact_whatsapp: "+254 731 144 822",
    location: "Mombasa",
    verified_only: true,
    work_type: "short-term-contract",
    urgency: "priority",
    status: "new",
    notes: "Peak tourism season support for protective styling and destination bridal weekends.",
    target_start_date: "2026-05-20",
    submitted_at: "2026-05-01T12:00:00.000Z",
  },
  {
    id: "req-atelier-editorial",
    salon_name: "Atelier Beauty House",
    contact_name: "Joan Kendi",
    contact_email: "joan@atelier.example",
    contact_whatsapp: "+254 700 200 909",
    location: "Nairobi",
    verified_only: true,
    work_type: "short-term-contract",
    urgency: "standard",
    status: "completed",
    notes: "Editorial launch campaign requiring a senior makeup artist with photography-set discipline.",
    target_start_date: "2026-04-18",
    submitted_at: "2026-04-05T09:00:00.000Z",
  },
  {
    id: "req-serene-rooms",
    salon_name: "Serene Rooms Spa",
    contact_name: "Linet Chebet",
    contact_email: "linet@serenerooms.example",
    contact_whatsapp: "+254 710 602 334",
    location: "Kisumu",
    verified_only: true,
    work_type: "long-term-contract",
    urgency: "standard",
    status: "completed",
    notes: "Treatment room rebuild after membership growth. Needed calm guest handling and strong consultation habits.",
    target_start_date: "2026-05-12",
    submitted_at: "2026-04-24T08:40:00.000Z",
  },
];

export const teamRequestRoles: TeamRequestRoleRecord[] = [
  { id: "trr-luna-hair", team_request_id: "req-luna-house", role: "Hair Stylist", quantity: 2, min_experience: 4 },
  { id: "trr-luna-nails", team_request_id: "req-luna-house", role: "Nail Technician", quantity: 1, min_experience: 3 },
  { id: "trr-baroque-barber", team_request_id: "req-baroque-grooming", role: "Barber", quantity: 2, min_experience: 5 },
  { id: "trr-coastline-braider", team_request_id: "req-coastline-beauty", role: "Braider", quantity: 2, min_experience: 4 },
  { id: "trr-coastline-makeup", team_request_id: "req-coastline-beauty", role: "Makeup Artist", quantity: 1, min_experience: 5 },
  { id: "trr-atelier-makeup", team_request_id: "req-atelier-editorial", role: "Makeup Artist", quantity: 1, min_experience: 6 },
  { id: "trr-serene-spa", team_request_id: "req-serene-rooms", role: "Spa Therapist", quantity: 1, min_experience: 6 },
];

export const teamRequestRoleSkills: TeamRequestRoleSkillRecord[] = [
  { id: "trrs-1", team_request_role_id: "trr-luna-hair", skill_id: "skill-color-correction" },
  { id: "trrs-2", team_request_role_id: "trr-luna-hair", skill_id: "skill-silk-press" },
  { id: "trrs-3", team_request_role_id: "trr-luna-nails", skill_id: "skill-gel-x" },
  { id: "trrs-4", team_request_role_id: "trr-luna-nails", skill_id: "skill-nail-art" },
  { id: "trrs-5", team_request_role_id: "trr-baroque-barber", skill_id: "skill-fades" },
  { id: "trrs-6", team_request_role_id: "trr-baroque-barber", skill_id: "skill-beards" },
  { id: "trrs-7", team_request_role_id: "trr-coastline-braider", skill_id: "skill-knotless" },
  { id: "trrs-8", team_request_role_id: "trr-coastline-braider", skill_id: "skill-boho-braids" },
  { id: "trrs-9", team_request_role_id: "trr-coastline-makeup", skill_id: "skill-bridal-makeup" },
  { id: "trrs-10", team_request_role_id: "trr-atelier-makeup", skill_id: "skill-editorial" },
  { id: "trrs-11", team_request_role_id: "trr-atelier-makeup", skill_id: "skill-airbrush" },
  { id: "trrs-12", team_request_role_id: "trr-serene-spa", skill_id: "skill-aromatherapy" },
];

export const staffingAssignments: StaffingAssignmentRecord[] = [
  {
    id: "assign-luna-amara",
    team_request_id: "req-luna-house",
    team_request_role_id: "trr-luna-hair",
    worker_id: "amara-njeri",
    status: "reserved",
    assigned_by: "Grace",
    assigned_at: "2026-05-05T11:00:00.000Z",
    notes: "Reserved after successful in-person demo and color consultation review.",
  },
  {
    id: "assign-luna-nadia",
    team_request_id: "req-luna-house",
    team_request_role_id: "trr-luna-nails",
    worker_id: "nadia-aziz",
    status: "reserved",
    assigned_by: "Grace",
    assigned_at: "2026-05-06T09:00:00.000Z",
    notes: "Reserved for opening-week manicure coverage.",
  },
  {
    id: "assign-luna-joy",
    team_request_id: "req-luna-house",
    team_request_role_id: "trr-luna-hair",
    worker_id: "joy-cherotich",
    status: "recommended",
    assigned_by: "Grace",
    assigned_at: "2026-05-06T14:00:00.000Z",
    notes: "Backup junior stylist once references clear.",
  },
  {
    id: "assign-baroque-baraka",
    team_request_id: "req-baroque-grooming",
    team_request_role_id: "trr-baroque-barber",
    worker_id: "baraka-otieno",
    status: "reserved",
    assigned_by: "Kevin",
    assigned_at: "2026-05-07T16:00:00.000Z",
    notes: "Client wants him held while finalizing second barber.",
  },
  {
    id: "assign-baroque-malik",
    team_request_id: "req-baroque-grooming",
    team_request_role_id: "trr-baroque-barber",
    worker_id: "malik-dube",
    status: "recommended",
    assigned_by: "Kevin",
    assigned_at: "2026-05-07T16:20:00.000Z",
    notes: "Recommended candidate for lead barber coverage.",
  },
  {
    id: "assign-atelier-zuri",
    team_request_id: "req-atelier-editorial",
    team_request_role_id: "trr-atelier-makeup",
    worker_id: "zuri-kamau",
    status: "hired",
    assigned_by: "Grace",
    assigned_at: "2026-04-10T10:00:00.000Z",
    notes: "Completed placement with strong client feedback.",
  },
  {
    id: "assign-serene-eshe",
    team_request_id: "req-serene-rooms",
    team_request_role_id: "trr-serene-spa",
    worker_id: "eshe-mwangi",
    status: "hired",
    assigned_by: "Grace",
    assigned_at: "2026-04-28T09:15:00.000Z",
    notes: "Placed and retained after trial week.",
  },
];

export const bookings: BookingRecord[] = [
  {
    id: "booking-luna-team",
    type: "team",
    title: "Luna House opening team",
    status: "confirmed",
    payment_status: "deposit_due",
    booking_date: "2026-05-28",
    submitted_at: "2026-05-08T10:15:00.000Z",
    worker_ids: ["amara-njeri", "nadia-aziz"],
    team_request_id: "req-luna-house",
    notes: "Two workers confirmed. Deposit is needed before start date.",
    payment_instructions: defaultPaymentInstructions({
      id: "booking-luna-team",
      type: "team",
      worker_count: 2,
    }),
    payment_verification: {
      status: "not_submitted",
      submitted_reference: null,
      verified_by: null,
      verified_at: null,
      notes: "Waiting for client payment reference.",
    },
  },
  {
    id: "booking-baroque-barbers",
    type: "team",
    title: "Baroque barber team",
    status: "pending",
    payment_status: "not_due",
    booking_date: "2026-06-05",
    submitted_at: "2026-05-09T08:30:00.000Z",
    worker_ids: ["baraka-otieno", "malik-dube"],
    team_request_id: "req-baroque-grooming",
    notes: "Beauty Connect is checking final worker availability.",
    payment_instructions: null,
    payment_verification: null,
  },
  {
    id: "booking-leila-single",
    type: "worker",
    title: "Leila Hassan single booking",
    status: "pending",
    payment_status: "not_due",
    booking_date: "2026-05-24",
    submitted_at: "2026-05-09T13:00:00.000Z",
    worker_ids: ["leila-hassan"],
    team_request_id: null,
    notes: "Single nail technician booking awaiting review.",
    payment_instructions: null,
    payment_verification: null,
  },
  {
    id: "booking-thando-single",
    type: "worker",
    title: "Thando Mbeki wig specialist",
    status: "confirmed",
    payment_status: "deposit_due",
    booking_date: "2026-05-25",
    submitted_at: "2026-05-07T15:45:00.000Z",
    worker_ids: ["thando-mbeki"],
    team_request_id: null,
    notes: "Worker confirmed. Deposit is pending.",
    payment_instructions: defaultPaymentInstructions({
      id: "booking-thando-single",
      type: "worker",
      worker_count: 1,
    }),
    payment_verification: {
      status: "submitted",
      submitted_reference: "MPESA-QF92",
      verified_by: null,
      verified_at: null,
      notes: "Client submitted reference. Admin verification pending.",
    },
  },
  {
    id: "booking-atelier-makeup",
    type: "worker",
    title: "Atelier makeup booking",
    status: "paid",
    payment_status: "deposit_paid",
    booking_date: "2026-04-18",
    submitted_at: "2026-04-05T09:00:00.000Z",
    worker_ids: ["zuri-kamau"],
    team_request_id: "req-atelier-editorial",
    notes: "Deposit paid. Booking moved to hires.",
    payment_instructions: defaultPaymentInstructions({
      id: "booking-atelier-makeup",
      type: "worker",
      worker_count: 1,
    }),
    payment_verification: {
      status: "verified",
      submitted_reference: "BC-PAY-4108",
      verified_by: "Grace",
      verified_at: "2026-04-17T12:00:00.000Z",
      notes: "Payment confirmed manually.",
    },
  },
  {
    id: "booking-serene-spa",
    type: "worker",
    title: "Serene Rooms spa therapist",
    status: "paid",
    payment_status: "deposit_paid",
    booking_date: "2026-05-12",
    submitted_at: "2026-04-24T08:40:00.000Z",
    worker_ids: ["eshe-mwangi"],
    team_request_id: "req-serene-rooms",
    notes: "Deposit paid. Worker is active.",
    payment_instructions: defaultPaymentInstructions({
      id: "booking-serene-spa",
      type: "worker",
      worker_count: 1,
    }),
    payment_verification: {
      status: "verified",
      submitted_reference: "BC-PAY-4124",
      verified_by: "Grace",
      verified_at: "2026-05-11T10:30:00.000Z",
      notes: "Payment confirmed manually.",
    },
  },
];

export const hires: HireRecord[] = [
  {
    id: "hire-atelier-makeup",
    booking_id: "booking-atelier-makeup",
    title: "Atelier makeup hire",
    status: "active",
    payment_status: "paid",
    hire_date: "2026-04-18",
    worker_ids: ["zuri-kamau"],
    payment_reference: "BC-PAY-4108",
  },
  {
    id: "hire-serene-spa",
    booking_id: "booking-serene-spa",
    title: "Serene Rooms spa hire",
    status: "active",
    payment_status: "paid",
    hire_date: "2026-05-12",
    worker_ids: ["eshe-mwangi"],
    payment_reference: "BC-PAY-4124",
  },
];

export const adminNotes: AdminNoteRecord[] = [
  {
    id: "note-1",
    worker_id: "aisha-noor",
    team_request_id: null,
    staffing_assignment_id: null,
    author: "Grace",
    note: "Waiting on updated government ID before verification can move from pending to verified.",
    created_at: "2026-05-06T10:20:00.000Z",
  },
  {
    id: "note-2",
    worker_id: "joy-cherotich",
    team_request_id: null,
    staffing_assignment_id: null,
    author: "Grace",
    note: "Reference was positive, but previous salon could only confirm part-time shift coverage so far.",
    created_at: "2026-05-06T12:20:00.000Z",
  },
  {
    id: "note-3",
    worker_id: "farah-juma",
    team_request_id: null,
    staffing_assignment_id: null,
    author: "Grace",
    note: "Reference contact could not verify bridal workload claims. Marked rejected until replacement documents arrive.",
    created_at: "2026-05-02T16:00:00.000Z",
  },
  {
    id: "note-4",
    worker_id: null,
    team_request_id: "req-luna-house",
    staffing_assignment_id: null,
    author: "Kevin",
    note: "Owner is open to staggering the second stylist by one week if the first two hires are strong.",
    created_at: "2026-05-05T13:45:00.000Z",
  },
  {
    id: "note-5",
    worker_id: null,
    team_request_id: "req-baroque-grooming",
    staffing_assignment_id: null,
    author: "Kevin",
    note: "Client cares more about chair pace and grooming etiquette than retail sales history.",
    created_at: "2026-05-07T15:15:00.000Z",
  },
  {
    id: "note-6",
    worker_id: null,
    team_request_id: "req-coastline-beauty",
    staffing_assignment_id: null,
    author: "Kevin",
    note: "Braiders should be able to handle longer destination booking blocks without extra support.",
    created_at: "2026-05-02T16:45:00.000Z",
  },
  {
    id: "note-7",
    worker_id: null,
    team_request_id: null,
    staffing_assignment_id: "assign-luna-amara",
    author: "Grace",
    note: "Reservation confirmed after compensation band matched candidate expectation.",
    created_at: "2026-05-05T11:15:00.000Z",
  },
];

export const adminActivityLogs: AdminActivityLogRecord[] = [
  {
    id: "activity-luna-confirmed",
    type: "booking_confirmed",
    actor: "Grace",
    message: "Confirmed Luna House opening team and moved workers to reserved.",
    booking_id: "booking-luna-team",
    worker_id: null,
    created_at: "2026-05-08T10:20:00.000Z",
  },
  {
    id: "activity-amara-reserved",
    type: "worker_reserved",
    actor: "Grace",
    message: "Reserved Amara Njeri for Luna House opening team.",
    booking_id: "booking-luna-team",
    worker_id: "amara-njeri",
    created_at: "2026-05-08T10:22:00.000Z",
  },
  {
    id: "activity-thando-payment-submitted",
    type: "payment_confirmed",
    actor: "Admin",
    message: "Payment reference MPESA-QF92 received for manual verification.",
    booking_id: "booking-thando-single",
    worker_id: "thando-mbeki",
    created_at: "2026-05-09T16:10:00.000Z",
  },
  {
    id: "activity-zuri-released",
    type: "worker_released",
    actor: "Grace",
    message: "Released Zuri Kamau contact details after deposit confirmation.",
    booking_id: "booking-atelier-makeup",
    worker_id: "zuri-kamau",
    created_at: "2026-04-17T12:05:00.000Z",
  },
  {
    id: "activity-eshe-hired",
    type: "worker_status_updated",
    actor: "Grace",
    message: "Updated Eshe Mwangi from reserved to hired after payment clearance.",
    booking_id: "booking-serene-spa",
    worker_id: "eshe-mwangi",
    created_at: "2026-05-11T10:34:00.000Z",
  },
];

export const verificationDocuments: VerificationDocumentRecord[] = [
  {
    id: "doc-1",
    worker_id: "amara-njeri",
    document_type: "National ID",
    status: "verified",
    file_url: "https://storage.example.com/amara-id.pdf",
    uploaded_at: "2026-04-29T10:00:00.000Z",
  },
  {
    id: "doc-2",
    worker_id: "amara-njeri",
    document_type: "Reference Letter",
    status: "verified",
    file_url: "https://storage.example.com/amara-reference.pdf",
    uploaded_at: "2026-04-30T10:00:00.000Z",
  },
  {
    id: "doc-3",
    worker_id: "aisha-noor",
    document_type: "National ID",
    status: "pending",
    file_url: "https://storage.example.com/aisha-id.pdf",
    uploaded_at: "2026-05-06T10:00:00.000Z",
  },
  {
    id: "doc-4",
    worker_id: "thando-mbeki",
    document_type: "Training Certificate",
    status: "verified",
    file_url: "https://storage.example.com/thando-certificate.pdf",
    uploaded_at: "2026-04-28T09:00:00.000Z",
  },
  {
    id: "doc-5",
    worker_id: "farah-juma",
    document_type: "Reference Letter",
    status: "rejected",
    file_url: "https://storage.example.com/farah-reference.pdf",
    uploaded_at: "2026-05-01T11:00:00.000Z",
  },
  {
    id: "doc-6",
    worker_id: "baraka-otieno",
    document_type: "National ID",
    status: "verified",
    file_url: "https://storage.example.com/baraka-id.pdf",
    uploaded_at: "2026-04-25T08:00:00.000Z",
  },
];
